-- 77 STAR
-- รันใน Supabase SQL Editor
create table if not exists public.tables (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz default now()
);

create table if not exists public.menus (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12,2) not null default 0,
  description text default '',
  created_at timestamptz default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  table_id bigint not null references public.tables(id) on delete restrict,
  items text not null default '[]',
  total numeric(12,2) not null default 0,
  status text not null default 'รออาหาร',
  created_at timestamptz default now()
);

-- สำหรับเวอร์ชันที่ไม่ใช้หน้า Login ตามที่ขอ
-- เปิดสิทธิ์ให้เว็บอ่าน/เพิ่ม/แก้/ลบได้
alter table public.tables enable row level security;
alter table public.menus enable row level security;
alter table public.orders enable row level security;

drop policy if exists "77star tables all" on public.tables;
create policy "77star tables all" on public.tables for all using (true) with check (true);

drop policy if exists "77star menus all" on public.menus;
create policy "77star menus all" on public.menus for all using (true) with check (true);

drop policy if exists "77star orders all" on public.orders;
create policy "77star orders all" on public.orders for all using (true) with check (true);

-- ตัวอย่างข้อมูลเริ่มต้น
insert into public.tables (name)
select 'โต๊ะ 1' where not exists (select 1 from public.tables);

insert into public.menus (name,price,description)
select 'ข้าวไก่เทอริยากิ', 129, 'ไก่เทอริยากิพร้อมข้าว'
where not exists (select 1 from public.menus);
